version: '3.8'

services:
  usermanagement:
    build:
      context: .
      dockerfile: Dockerfile
    image: zanzibarinh/usermanagement:latest
    container_name: UserManagement
    ports:
      - "8080:80"