apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\bashu\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -c
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: usermanagement
  name: usermanagement
  namespace: kawa-foundation-app-dev
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: usermanagement
status:
  loadBalancer: {}
