apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\bashu\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -c
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: user-api
  name: user-api
  namespace: default
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    io.kompose.service: user-api
status:
  loadBalancer: {}
