apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\bashu\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -c
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: usermanagement
  name: usermanagement
  namespace: kawa-foundation-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: usermanagement
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\bashu\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -c
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/usermanagement-default: "true"
        io.kompose.service: usermanagement
    spec:
      containers:
        - image: zanzibarinh/usermanagement:latest
          name: usermanagement
          resources: {}
      restartPolicy: Always
status: {}
