name: um-dev-pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v7
        with:
          dotnet-version: 6.0.100

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test

  docker:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t your-image-name:latest .
          docker tag your-image-name:latest your-dockerhub-username/your-image-name:latest
          docker push your-dockerhub-username/your-image-name:latest

  deploy:
    runs-on: ubuntu-latest

    needs: docker

    steps:
      - name: Deploy to OpenShift
        run: |
          # Your OpenShift deployment commands go here
