name: um-dev-pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./UserManagement

      - name: Build
        run: dotnet build --no-restore
        working-directory: ./UserManagement

      # - name: Test
      #   run: dotnet test --no-build --verbosity normal
      #   working-directory: ./UserManagement

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          buildkit: true
          push: true
          platforms: linux/amd64,linux/arm64
          tags: zanzibarinh/usermanagement:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Login to OpenShift
        run: oc login --server="${OPENSHIFT_SERVER}" --token="${OPENSHIFT_TOKEN}" --insecure-skip-tls-verify
        with:
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      
      - name: Set the OpenShift project/namespace
        run: oc project "${OPENSHIFT_NAMESPACE}"
        with:
          OPENSHIFT_NAMESPACE: kawa-foundation-app-dev
      
      - name: Clone the git repo
        run: git clone "${GITREPO}"
        with:
          GITREPO: https://github.com/ZanzibarNature/UserManagement.git
      
      - name: Navigate to the repository directory
        run: cd UserManagement/
      
      - name: Checkout the dev branch
        run: git checkout dev
      
      - name: Deploy using Helm
        run: helm upgrade user-management docker-compose/
